name 'dstockman-stackdriver'
version '1.1.0'
source 'git@github.com:maverixbio/puppet-stackdriver-agent.git'
author 'denise stockman'
description 'Puppet module to install stackdriver'
project_page 'https://github.com/maverixbio/puppet-stackdriver-agent'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'puppetlabs/registry', '>= 1.0.0'
dependency 'joshcooper/powershell', '>= 0.0.6'
